#version: '3.8'
#
#services:
#  nonprofit-grader:
#    image: nonprofit-grader:latest
#    build: .
#    volumes:
#        - ./nonprofit-grader:/home/appuser/nonprofit-grader
#        - ./data:/home/appuser/data
#    env_file:
#      - .env
#    ports:
#      - "${APP_PORT:-7860}:${APP_PORT:-7860}"
#    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=${APP_PORT:-7860}", "--no-browser"]
##    command: ["/bin/bash"]
##    command: [
##      "streamlit", "run",
##      "/home/appuser/nonprofit-grader/frontend/frontend/app.py",
##      "--server.port", "${APP_PORT:-7860}",
##      "--server.address", "0.0.0.0"
##    ]


version: '3'

services:

  backend:
    build:
      context: nonprofit-grader/backend
    container_name: backend-service
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT:-7860}"
    working_dir: /home/appuser/nonprofit-grader/backend
    volumes:
      - ./nonprofit-grader/backend/backend:/home/appuser/nonprofit-grader/backend
    networks:
      - nonprofit-grader-network
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT:-7860}"]

  frontend:
    build: nonprofit-grader/frontend
    container_name: frontend-service
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT:-7860}"
    working_dir: /home/appuser/nonprofit-grader/frontend
    volumes:
      - ./nonprofit-grader/frontend/frontend:/home/appuser/nonprofit-grader/frontend
    networks:
      - nonprofit-grader-network
    depends_on: 
      - backend
    command: ["streamlit", "run", "/home/appuser/nonprofit-grader/frontend/app.py", "--server.port", "${FRONTEND_PORT:-7860}", "--server.address", "0.0.0.0"]
networks:
  nonprofit-grader-network:
    driver: bridge
